### ISSUE TITLE
'latest' tag is missing

### ISSUE THREAD

**Issue by Mist-Hunter** [linuxserver/docker-prowlarr#16]
docker pull linuxsinuxserver/prowlarr:latest
Error response from daemon: pull access denied for linuxserver/prowlarr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Other tags work fine.

**Comment by aptalca** [comment]
Per the readme, there is no latest tag: https://github.com/linuxserver/docker-prowlarr#version-tags
