### ISSUE TITLE
Specify the tag in the Docker Compose Usage template

### ISSUE THREAD

**Issue by sofronaspe** [linuxserver/docker-prowlarr#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Specify the tag in the Docker Compose Usage template
------------------------------

## Desired Behavior

When running the Docker Compose example listed in the README, the prowlarr image should be pulled
## Current Behavior

Copying and pasting the code directly does not specify a tag, so docker tries to pull from \:latest which does not exist #16 
## Alternatives Considered

I looked through the docker documentation for specifying an image tag, and would recommend changing the following line
`    image: lscr.io/linuxserver/prowlarr`
to
`    image: lscr.io/linuxserver/prowlarr:tag #Specify the develop or nightly tag`

**Comment by Roxedus** [comment]
No plans to change this. There is no stable release of Prowlarr yet, so we would like users to read the whole readme to get going.
