### ISSUE TITLE
Password - Enviroment not working?

### ISSUE THREAD

**Issue by Smiggel** [linuxserver/docker-prowlarr#29]
I followed the instructions to set up Prowlarr. It works fine.

However, I want it to be password protected. So I set the FILE__PASSWORD environment variable:
- FILE__PASSWORD=/srv/dev-disk-by-uuid-1142b02c-af65-4945-9888-42ac0f50d487/Data/Prowlarr/passwd

The path is to a custom folder on the server. Then started the stack build again. Prowlarr runs again, but I see no password and am able to access the interface without it. 

Am I doing something wrong or is the password check not working? I see no errors in the logs.

**Comment by j0nnymoe** [comment]
There is no password variable for prowlarr.

**Comment by Smiggel** [comment]
What is the Environment variables from files (Docker secrets) for then in the documentation?

**Comment by j0nnymoe** [comment]
It's an example. If there are environment variables listed within the docker-compose/run snippet then you can use docker secrets to set them.

**Comment by aptalca** [comment]
Even if there was, the path would need to be a path inside the container, not on host.
