### ISSUE TITLE
"Prowlarr updated" modal won't close on 1.0.0.2171

### ISSUE THREAD

**Issue by raspberrycoulis** [linuxserver/docker-prowlarr#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The modal should disappear when you click "Reload" as per the advice in the message.

## Current Behavior
The modal reappears after clicking "Reload". Even forcing a browser cache refresh does not work.

## Steps to Reproduce
1. Updated to version 1.0.0.2171 from 0.4.11.2143 using the Docker imge.
2. Loaded the interface after updating
3. Voila

## Environment
**OS:** Docker on Synology NAS (DS718+)
**CPU architecture:** x86_64
**How docker service was installed:**
Installed via Docker Compose - has been working fine until the recent update.

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Prowlarr: https://opencollective.com/prowlarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    101
-------------------------------------

---------------------------
|  Prowlarr theme.park Mod  |
---------------------------
Variables set:
'TP_DOMAIN'=
'TP_COMMUNITY_THEME'=
'TP_SCHEME'=
'TP_ADDON'=
'TP_THEME'=space-gray

No domain set, defaulting to theme-park.dev
No scheme set, defaulting to https
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 1.0.0.2171
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Debug] Bootstrap: Console selected
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] MigrationController: *** Migrating data source=/config/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] CommandExecutor: Starting 3 threads for tasks.
[ls.io-init] done.
```

**Comment by Roxedus** [comment]
Try clearing the cache for the site in your browser. 
Closing as this is at best, not a container issue, but a application issue.

**Comment by raspberrycoulis** [comment]
I already said that I tried flushing the browser cache but it didn't work. I've also since tried this in a private tab, on my mobile using 4G instead of WiFi and on different browsers but the modal issue remains.
