### ISSUE TITLE
[BUG] Image incorrectly tagged with version `1.8.1259` throws off tools relying on semantic versioning

### ISSUE THREAD

**Issue by EricRibeiro** [linuxserver/docker-prowlarr#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An [image](https://hub.docker.com/layers/linuxserver/prowlarr/1.8.1259/images/sha256-9af25e5a3d9ffae44726ecf4d1e2db21b3c389ff8c2d242e295988b7f3d14a49?context=explore) released one year ago was tagged with "1.8.1259". Prowlarr's latest version is "1.3.2.3006".

Tools reliant on semantic versioning, like Renovate, think the latest release is v1.8.1259 and open a PR to update the image. You can see it happening here: https://github.com/EricRibeiro/raspberry-docker-compose-collection/pull/17.

### Expected Behavior

I believe the correct tag for that particular release is "0.1.8.1259". Ideally, that specific tag should be deleted to avoid confusion.

### Steps To Reproduce

1. Run Renovate with the default configuration.

### Environment

```markdown
N/A
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
Dupe #42
