### ISSUE TITLE
[BUG] NFS option "nocopy" not working

### ISSUE THREAD

**Issue by dmcg10** [linuxserver/docker-prowlarr#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've recently switched most of my containers to using Docker Volumes (`docker volume create`) that are backed by NFS. I've copied the same config to all of my services and Prowlarr is the only service that fails to mount with the NFS "nocopy" option.

Terminal error output:
```shell
user@debian-server:~/docker/test$ sudo docker compose -f docker-compose.yml up -d prowlarr && sudo docker logs -f prowlarr
[+] Running 4/4
 ✔ Network test     Created                                                                                                                   0.1s
 ✔ Volume "prowlarr"       Created                                                                                                                   0.0s
 ⠋ Container prowlarr      Creating                                                                                                                  0.0s
Error response from daemon: failed to mount local volume: mount :/volume1/Docker/containers/prowlarr/config:/var/lib/docker/volumes/prowlarr/_data, data: addr=10.10.10.50,nolock,nocopy,hard: invalid argument
```

As soon as the "nocopy" option is removed, the container volume mounts fine.

Compose file:
```dockerfile
version: "3.6"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1024
      - PGID=101
      - TZ=Etc/UTC
    volumes:
      - prowlarr:/config
    depends_on:
      - flaresolverr
    restart: unless-stopped

networks:
  test:
    name: test

  prowlarr:
    name: prowlarr
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.10.10.50,nolock,rw,async,nocopy,hard"
      device: ":/volume1/Docker/containers/prowlarr/config"

``` 

### Expected Behavior

The container should have no issue supporting the NFS "nocopy" option.

### Steps To Reproduce

1. Create NFS share and export
2. Create docker-compose file with options show above
3. Run container with docker compose

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- How docker service was installed: https://get.docker.com/
```

### CPU architecture

x86-64

### Docker creation

```bash
sudo docker compose -f docker-compose.yml up -d prowlarr
```

### Container logs

```bash
There is no docker logs because the container fails to start due to the NFS "nocopy" option
```

**Comment by aptalca** [comment]
We do not support or recommend putting config folders on file/object based remote storage for various reasons. Databases especially do not like file/object based remote mounts. Block storage on the other hand should be fine.
