### ISSUE TITLE
Container deployment fails - AppFolder /config is not writable

### ISSUE THREAD

**Issue by jpcapone** [linuxserver/docker-prowlarr#6]
I am using portainer to deploy the docker for prowlarr.  The container never became available via the web portal so i started digging into the logs.  What I found is that the it isn't starting because of this error below:
[v0.1.0.608] NzbDrone.Common.Exceptions.ProwlarrStartupException: Prowlarr failed to start: AppFolder /config is not writable,
I have tried a bunch of different things but I continue to get the same result.  Has anyone else experienced this issue?

**Comment by kavemang** [comment]
Hi, attached is my log from what I think is the same issue

[_prowlarr_logs.txt](https://github.com/linuxserver/docker-prowlarr/files/6838458/_prowlarr_logs.txt)

**Comment by j0nnymoe** [comment]
@kavemang you've commented on a closed ticket. Please open a new one and provide all the information it requests.

**Comment by jpcapone** [comment]
This happened to me because my hard drive was full.  I am not exactly sure how the drive because full so quickly but thats another issue.
