### ISSUE TITLE
Installation instructions are invalid (404 reference)

### ISSUE THREAD

**Issue by digdilem** [linuxserver/docker-prowlarr#7]
The docker-compose file on the landing page for this project uses this url

`lscr.io/linuxserver/prowlarr`

This is 404, and when tried results in 

`ERROR: manifest unknown`

Project looks active, so presumably just a documentation change.

**Comment by j0nnymoe** [comment]
Nope, there is just no `:latest` currently https://github.com/linuxserver/docker-prowlarr#version-tags
