### ISSUE TITLE
Basic and Forms security causes the webpage to fail to load

### ISSUE THREAD

**Issue by v6-cblais** [linuxserver/docker-prowlarr#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Like the other *arrs this should enable the security page or browser popup as selected
## Current Behavior

After mandatory restart a 502 error is displayed.
## Steps to Reproduce

1. bring up docker container
2. enabled security (either basic or form)
3. restart container (either from gui or docker commands)
4. Permanent 502 error

## Environment
**OS:** 5.4.0-89-generic #100-Ubuntu 
**CPU architecture:** x86_64
**How docker service was installed:**

docker-compose from the example, traefik labels added on. Config is basically the same as the other *arr applications.

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /mnt/FS:/FS
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.domain.com`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  default:
  traefik:
    external: true

## Docker logs

docker-compose logs -f
Attaching to prowlarr
prowlarr    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
prowlarr    | [s6-init] ensuring user provided files have correct perms...exited 0.
prowlarr    | [fix-attrs.d] applying ownership & permissions fixes...
prowlarr    | [fix-attrs.d] done.
prowlarr    | [cont-init.d] executing container initialization scripts...
prowlarr    | [cont-init.d] 01-envfile: executing... 
prowlarr    | [cont-init.d] 01-envfile: exited 0.
prowlarr    | [cont-init.d] 10-adduser: executing... 
prowlarr    | 
prowlarr    | -------------------------------------
prowlarr    |           _         ()
prowlarr    |          | |  ___   _    __
prowlarr    |          | | / __| | |  /  \
prowlarr    |          | | \__ \ | | | () |
prowlarr    |          |_| |___/ |_|  \__/
prowlarr    | 
prowlarr    | 
prowlarr    | Brought to you by linuxserver.io
prowlarr    | -------------------------------------
prowlarr    | 
prowlarr    | To support the app dev(s) visit:
prowlarr    | Prowlarr: https://opencollective.com/prowlarr
prowlarr    | 
prowlarr    | To support LSIO projects visit:
prowlarr    | https://www.linuxserver.io/donate/
prowlarr    | -------------------------------------
prowlarr    | GID/UID
prowlarr    | -------------------------------------
prowlarr    | 
prowlarr    | User uid:    0
prowlarr    | User gid:    0
prowlarr    | -------------------------------------
prowlarr    | 
prowlarr    | [cont-init.d] 10-adduser: exited 0.
prowlarr    | [cont-init.d] 30-config: executing... 
prowlarr    | [cont-init.d] 30-config: exited 0.
prowlarr    | [cont-init.d] 90-custom-folders: executing... 
prowlarr    | [cont-init.d] 90-custom-folders: exited 0.
prowlarr    | [cont-init.d] 99-custom-scripts: executing... 
prowlarr    | [custom-init] no custom files found exiting...
prowlarr    | [cont-init.d] 99-custom-scripts: exited 0.
prowlarr    | [cont-init.d] done.
prowlarr    | [services.d] starting services
prowlarr    | [services.d] done.
prowlarr    | [Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 0.1.5.1164 
prowlarr    | [Debug] Bootstrap: Getting windows service status 
prowlarr    | [Debug] Bootstrap: Console selected 
prowlarr    | [Info] AppFolderInfo: Data directory is being overridden to [/config] 
prowlarr    | [Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
prowlarr    | [Info] AppFolderInfo: Data directory is being overridden to [/config] 
prowlarr    | [Warn] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {f46616a0-b163-49fe-b6c4-cf6954920b3a} may be persisted to storage in unencrypted form. 
prowlarr    | [Info] MigrationController: *** Migrating data source=/config/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
prowlarr    | [Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
prowlarr    | [Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:8181 
prowlarr    | [Info] CommandExecutor: Starting 3 threads for tasks. 
prowlarr    | [Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
prowlarr    | [Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
prowlarr    | [Info] Microsoft.Hosting.Lifetime: Content root path: /app/prowlarr/bin

**Comment by drizuid** [comment]
couple things here
1) 502 means you cant reach the service
2) you show this
```
- PUID=1000
- PGID=10000
```
but your logs show
```
prowlarr | User uid: 0
prowlarr | User gid: 0
```
in the event that your compose setting doesnt carry through, it shows 911. this means you actually set your puid/pgid to 0 (which is unsupported)  Please show us the compose you used to generate the logs you provide (note, you must stop/rm the container to change some compose settings)
3) we don't offer any support for traefik at all, and this is most likely the source of your issue. if you'd like to use swag and request support, we're happy to help. 

barring an update which does not include traefik in the tshoot process, i will close this as an unsupported setup. Best to seek assistance from the traefik devs on why it returns a 502.
